name: Node CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install
        run: npm install

      - name: Test
        run: npm run test
      #- name: codecov
      #  run: npx codecov
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
